---
- name: 'WEB Server configure playbook'
  hosts: elk
  become: true


  tasks:

    - name: Set timezone
      timezone:
        name: Europe/Moscow  

    - name: Remove default route
      lineinfile:
        line: "DEFROUTE=no"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0

    - name: Add gateway
      lineinfile:
        line: "GATEWAY=192.168.10.10"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1  
      notify:
        - restart network

    - name: Epel release
      yum:
        name: epel-release
        state: present

    - name: Add ELK Repository
      yum_repository:
        name: elasticsearch-7
        description: ELK
        file: elasticserach.repo
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: true
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: true 

    - name: 'Install ELK'
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - elasticsearch 
        - kibana
        - logstash

    - name: 'Config ELK'
      lineinfile:
        path:  "{{ item.path }}" 
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { path: '/etc/elasticsearch/elasticsearch.yml', regexp: '^#cluster.name:', line: 'cluster.name: elk'}
        - { path: '/etc/elasticsearch/elasticsearch.yml', regexp: '^#node.name:', line: 'node.name: elk'}
        - { path: '/etc/elasticsearch/elasticsearch.yml', regexp: '^#network.host:', line: 'network.host: 0.0.0.0'}
        - { path: '/etc/elasticsearch/elasticsearch.yml', regexp: '^#cluster.initial_master_nodes:', line: 'cluster.initial_master_nodes: ["elk"]'}
        - { path: '/etc/elasticsearch/elasticsearch.yml', regexp: '^#http.port:', line: 'http.port: 9200'}
        - { path: '/etc/kibana/kibana.yml', regexp: '^#server.host:', line: 'server.host: 0.0.0.0'}
        - { path: '/etc/kibana/kibana.yml', regexp: '^#server.port', line: 'server.port: 5601'}
        - { path: '/etc/kibana/kibana.yml', regexp: '^#elasticsearch.hosts:', line: 'elasticsearch.hosts: ["http://localhost:9200"]'}
      notify:
        - restart elk


    - name: Firewalld service - firewalld is running
      systemd:
        name: firewalld
        enabled: true
        state: started  

    - name: Add port to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 5601/tcp
        - 9200/tcp
        - 9300/tcp

    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded       

  ############## Zabbix ###################

    - name: install the Zabbix repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: yum-clean-all
      command: yum clean all
      args:
        warn: no  

    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent
        state: present   

    - name: 'Config Zabbix Agent'
      lineinfile:
        path:  /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=127.0.0.1', line: 'Server=192.168.10.50'}
        - { regexp: '^Hostname=', line: 'Hostname=elk'}
      notify:
        - restart zabbix

    - firewalld:
        service: zabbix-agent
        permanent: yes
        state: enabled        
    
    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded         


  handlers:

    - name: restart elk 
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      loop:
        - elasticsearch.service
        - kibana.service
        - logstash.service

    - name: restart network
      service:
        name: network
        state: restarted           
    
    - name: restart zabbix
      systemd:
        name: zabbix-agent
        state: restarted                