---
- name: 'Router configure playbook'
  hosts: router
  become: true


  tasks:

    - name: Set timezone
      timezone:
        name: Europe/Moscow

    - name: 'Config sysctl ip_forward'
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      notify:
        - restart network 

    - name: Firewalld service - firewalld is running
      systemd:
        name: firewalld
        enabled: true
        state: started  

    - name: Add Masquerade
      firewalld:
        masquerade: true
        state: enabled
        permanent: true

    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded    


  ############## Zabbix Agent###################

    - name: install the Zabbix repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: yum-clean-all
      command: yum clean all
      args:
        warn: no  

    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent
        state: present   

    - name: 'Config Zabbix Agent'
      lineinfile:
        path:  /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=127.0.0.1', line: 'Server=192.168.10.50'}
        - { regexp: '^Hostname=', line: 'Hostname=router'}
      notify:
        - restart zabbix

    - firewalld:
        service: zabbix-agent
        permanent: yes
        state: enabled        
    
    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded         

  handlers:
    - name: restart network
      systemd:
        name: network
        state: restarted 

    - name: restart zabbix
      systemd:
        name: zabbix-agent
        state: restarted               