---
- name: 'DataBase Server configure playbook'
  hosts: mysql
  become: true

  vars:
    mysql_password: "Pa$$w0rd"

  
  tasks:

    - name: Set timezone
      timezone:
        name: Europe/Moscow   
    
    #### Network settings
    - name: Remove default route
      lineinfile:
        line: "DEFROUTE=no"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0

    - name: Add gateway
      lineinfile:
        line: "GATEWAY=192.168.10.10"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1

    #### iSCSI config
    - name: Epel release
      yum:
        name: epel-release
        state: present

    - name: 'Install packages'
      yum:
        name: iscsi-initiator-utils 
        state: 'present'
      notify:
        - restart iscsi 

    - name: Connect iSCSI disk
      shell: "iscsiadm -m discovery -t sendtargets -p 192.168.10.100 && iscsiadm -m node --login"

    - name: Create a directory
      file:
        path: /var/lib/mysql
        state: directory

    - name: Parted iSCSI disk
      shell: |
        parted -s /dev/sdb mklabel gpt
        parted /dev/sdb mkpart primary ext4 0% 100%
        mkfs.ext4 /dev/sdb1 
        mount -t ext4 /dev/sdb1 /var/lib/mysql 
   
             
    #### MySQL config   
    - name: Add MariaDB Repository
      yum_repository:
        name: MariaDB
        description: MariaDB
        file: MariaDB.repo
        baseurl: http://yum.mariadb.org/10.4/centos7-amd64
        gpgcheck: true
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        enabled: true 

    - name: install mysql (mariadb)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - mariadb-server
        - MySQL-python

    - name: Create a directory
      file:
        path: /var/log/mysql
        owner: mysql
        group: mysql
        state: directory        

    - name: enable mysql (mariadb)
      systemd:
        name: mariadb
        state: restarted
        enabled: yes

    - name: 'mysql_root_password'
      mysql_user:
        login_user: root
        login_password: "{{ mysql_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_password }}"
        host: localhost
      no_log: true  

    - name: 'root password'
      blockinfile:
        path: ~/.my.cnf
        create: yes
        block: |
          [client]
          user=root
          password={{ mysql_password }}      

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
      no_log: true   

    - name: test database is absent
      mysql_db:
        name: test
        state: absent    

    - name: create mysql client user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_password }}"
        name: "meno"
        password: "{{ mysql_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
        host: '%'
      no_log: true   


    - name: create mysql zabbix user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_password }}"
        name: "zabbix"
        password: 'zabbix'
        priv: 'zabbix.*:ALL,GRANT'
        state: present
        host: '%'
      no_log: true    

    # - name: 'Change my.cnf'
    #   replace:
    #     path: /etc/my.cnf.d/server.cnf
    #     regexp: '#bind-address=0.0.0.0'
    #     replace: 'bind-address=0.0.0.0'
    #   notify:
    #     - restart mariadb

    - name: 'Config MariaDB'
      copy: 
        src: conf/mysql-small.cnf 
        dest: /etc/my.cnf.d/mysql-small.cnf
      notify:
        - restart mariadb

    - name: Create a new database with name 'wordpress'
      mysql_db:
        name: wordpress
        state: present        


    - name: Create a new database 'zabbix'
      mysql_db:
        name: zabbix
        state: present        


    - name: 'Enable MySQL in Firewalld'
      firewalld:
        service: mysql
        permanent: yes
        state: enabled 

    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded 


    #### ELK Filebeat
    - name: Add ELK Repository
      yum_repository:
        name: elasticsearch-7
        description: ELK
        file: elasticserach.repo
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: true
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: true     

    - name: 'Install Filebeat'
      yum:
        name: filebeat
        state: present

    - name: 'Configure Filebeat'
      copy: 
        src: conf/filebeat.yml 
        dest: /etc/filebeat/filebeat.yml
      notify:
        - restart filebeat

    - name: 'Filebeat MySQL'
      shell: |
        filebeat modules enable mysql   
        filebeat setup
      notify:
        - restart filebeat 

  ############## Zabbix ###################

    - name: install the Zabbix repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: yum-clean-all
      command: yum clean all
      args:
        warn: no  

    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent
        state: present   

    - name: 'Config Zabbix Agent'
      lineinfile:
        path:  /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=127.0.0.1', line: 'Server=192.168.10.50'}
        - { regexp: '^Hostname=', line: 'Hostname=mysql'}
      notify:
        - restart zabbix

    - firewalld:
        service: zabbix-agent
        permanent: yes
        state: enabled        
    
    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded         

  handlers: 

    - name: restart mariadb
      systemd:
        name: mariadb
        enabled: yes
        state: restarted 

    - name: restart rpcbind
      systemd:
        name: rpcbind
        enabled: yes
        state: restarted   

    - name: restart iscsi 
      systemd:
        name: iscsid
        enabled: yes
        state: restarted

    - name: restart filebeat 
      systemd:
        name: filebeat
        enabled: yes
        state: restarted            

    - name: restart zabbix
      systemd:
        name: zabbix-agent
        state: restarted                         