---
- name: 'Install NFS Utils'
  yum:
    name: nfs-utils
    state: present
  notify:
    - restart rpcbind  

- name: Create a directory
  file:
    path: /mnt/backup
    state: directory

- name: 'NFS Systemd config'  
  copy: 
    src: files/mnt-share.mount 
    dest: /etc/systemd/system/mnt-share.mount

  
- name: 'Mount backup folder'
  shell: |
    mount -t nfs -o tcp 192.168.10.90:/var/nfs/ /mnt/backup/
  notify:
    - restart nfs 