---
- name: iSCSI Server configure playbook
  hosts: storage
  become: true
  
  tasks:

    - name: Set timezone
      timezone:
        name: Europe/Moscow

    #### Network settings
    - name: Remove default route
      lineinfile:
        line: "DEFROUTE=no"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0


    - name: Add gateway
      lineinfile:
        line: "GATEWAY=192.168.10.10"
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1    


    #### Congig LVM and mount 
    - name: Epel release
      yum:
        name: epel-release
        state: present

    - name: 'Install packages'
      yum:
        name: "{{ item }}"
        state: 'present'
      loop:
        - lvm2
        - scsi-target-utils
        - dkms
        - setools
        - policycoreutils-python  
      notify:
        - restart iscsi  

    - name: Create volume group on /dev/sdb and /dev/sdc
      lvg:
        vg: vg01
        pvs: /dev/sdb,/dev/sdc
        state: present

    - name: Create a logical volume of 2048m with disks /dev/sda and /dev/sdb
      lvol:
        vg: vg01
        lv: otus
        size: '3072'
        pvs: /dev/sdb,/dev/sdc
        opts: -m1
        state: present

    - name: Create a ext4 filesystem on LVM
      filesystem:
        fstype: ext4
        dev: /dev/vg01/otus 

    - name: Create a directory for iSCSI
      file:
        path: /var/lib/iscsi_disks
        state: directory

    - name: Mount up device
      mount:
        path: /var/lib/iscsi_disks
        src: /dev/vg01/otus
        fstype: ext4
        state: present

    - name: mount all
      command: mount -a
      args:
        warn: no
      become: true        

    #### iSCSI config

    - name: Allow SELinux change context
      command: "chcon -R -t tgtd_var_lib_t /var/lib/iscsi_disks"

    - name: Allow SELinux fcontext
      command: "semanage fcontext -a -t tgtd_var_lib_t /var/lib/iscsi_disks"      

    - name: Create disk 
      command: dd if=/dev/zero of=/var/lib/iscsi_disks/disk01.img bs=1M count=2048      

    - name: 'iSCSI Target Congig'
      copy: 
        src: conf/target01.conf 
        dest: /etc/tgt/conf.d/target01.conf
      notify:
        - restart iscsi  

    #### Firewall settings    
    - name: Firewalld service - firewalld is running
      systemd:
        name: firewalld
        enabled: true
        state: started  

    - name: 'Enable iSCSI service in Firewalld'
      firewalld:
        service: iscsi-target
        permanent: yes
        state: enabled
  
    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded 


  ############## Zabbix ###################

    - name: install the Zabbix repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: yum-clean-all
      command: yum clean all
      args:
        warn: no  

    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent
        state: present   

    - name: 'Config Zabbix Agent'
      lineinfile:
        path:  /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=127.0.0.1', line: 'Server=192.168.10.50'}
        - { regexp: '^Hostname=', line: 'Hostname=iscsi'}
      notify:
        - restart zabbix

    - firewalld:
        service: zabbix-agent
        permanent: yes
        state: enabled        
    
    - name: 'Reload Firewalld'
      systemd:
        name: firewalld
        state: reloaded          

  handlers:

    - name: restart iscsi 
      systemd:
        name: tgtd
        enabled: yes
        state: restarted
       
    - name: restart zabbix
      systemd:
        name: zabbix-agent
        state: restarted         