---
- name: 'Playbook to configure stand'
  hosts: all
  become: true

- import_playbook: playbook-router.yml
- import_playbook: playbook-elk.yml
- import_playbook: playbook-iscsi.yml 
- import_playbook: playbook-mysql.yml 
- import_playbook: playbook-web.yml 
- import_playbook: playbook-zabbix.yml